/**
 * sim/report — tally many {@link RunResult}s into a balance MARKDOWN report.
 *
 * The central metric is LIFT: win-rate of runs that OWNED a relic minus win-rate
 * of runs that did NOT. A strongly positive lift on a relic that's also
 * frequently owned = DOMINANT (the bot wins when it has it). Near-zero / negative
 * lift, or "offered a lot but rarely bought / never owned in a win" = DEAD.
 *
 * Caveats (surfaced in the report): the bot is a naive greedy player; lift is a
 * correlational signal, not a controlled A/B (relics co-occur, and a policy that
 * hoards relics owns most of the pool per run — which flattens lift). We report
 * offered-vs-owned + owned-win-rate alongside lift so the reader can judge.
 */
import { DRAFT_POOL } from "../run/cards.js";
import type { RunResult } from "./run.js";
import type { ShopPolicy } from "./policy.js";

export interface RelicStat {
  id: string;
  name: string;
  rarity: string;
  offered: number;
  owned: number;
  ownedWins: number;
  winRateWith: number;
  winRateWithout: number;
  lift: number;
}

export interface Aggregate {
  runs: number;
  wins: number;
  winRate: number;
  avgAnte: number;
  anteDist: number[]; // index 0..5 (0 unused); count of runs whose max ante == i
  relics: RelicStat[];
}

const NAME = new Map(DRAFT_POOL.map((c) => [c.id, c.name] as const));
const RARITY = new Map(DRAFT_POOL.map((c) => [c.id, c.rarity] as const));

export function aggregate(results: readonly RunResult[]): Aggregate {
  const runs = results.length;
  const wins = results.filter((r) => r.win).length;

  const anteDist = [0, 0, 0, 0, 0, 0];
  let anteSum = 0;
  for (const r of results) {
    anteSum += r.anteReached;
    anteDist[r.anteReached] = (anteDist[r.anteReached] ?? 0) + 1;
  }

  const stats: RelicStat[] = DRAFT_POOL.map((card) => {
    let offered = 0;
    let owned = 0;
    let ownedWins = 0;
    let notOwned = 0;
    let notOwnedWins = 0;
    for (const r of results) {
      const has = r.ownedRelics.includes(card.id);
      if (r.offeredRelics.includes(card.id)) offered++;
      if (has) {
        owned++;
        if (r.win) ownedWins++;
      } else {
        notOwned++;
        if (r.win) notOwnedWins++;
      }
    }
    const winRateWith = owned > 0 ? ownedWins / owned : 0;
    const winRateWithout = notOwned > 0 ? notOwnedWins / notOwned : 0;
    return {
      id: card.id,
      name: NAME.get(card.id) ?? card.id,
      rarity: RARITY.get(card.id) ?? "?",
      offered,
      owned,
      ownedWins,
      winRateWith,
      winRateWithout,
      lift: winRateWith - winRateWithout,
    };
  });

  return {
    runs,
    wins,
    winRate: runs > 0 ? wins / runs : 0,
    avgAnte: runs > 0 ? anteSum / runs : 0,
    anteDist,
    relics: stats,
  };
}

const pct = (n: number) => `${(n * 100).toFixed(1)}%`;
const signPct = (n: number) => `${n >= 0 ? "+" : ""}${(n * 100).toFixed(1)}%`;

export function renderMarkdown(
  agg: Aggregate,
  meta: { policy: ShopPolicy; stake: number; minOwnedForLift: number; elapsedMs: number; wordCount: number },
): string {
  const { policy, stake, minOwnedForLift, elapsedMs, wordCount } = meta;
  const L: string[] = [];

  L.push("# LEXICON — Challenge Balance Simulation");
  L.push("");
  L.push(
    `Auto-generated by the headless balance bot (\`src/sim/\`). A greedy bot plays ` +
      `${agg.runs} full Challenge runs at **Stake ${stake}**, always playing the ` +
      `highest-scoring legal word each play (real \`scoreWord\` engine) and buying ` +
      `relics via the **"${policy.label}"** shop policy. Scoring, the ante ladder, ` +
      `bosses, modifiers, deck-dealing and the shop economy are the REAL game code — ` +
      `this is the game's own math, not a re-model.`,
  );
  L.push("");

  // ── Headline ──
  L.push("## Headline");
  L.push("");
  L.push(`- **Runs:** ${agg.runs}`);
  L.push(`- **Overall win-rate:** ${pct(agg.winRate)} (${agg.wins}/${agg.runs})`);
  L.push(`- **Average ante reached:** ${agg.avgAnte.toFixed(2)} / 5`);
  L.push(
    `- **Ante-reached distribution:** ` +
      agg.anteDist
        .map((c, i) => (i === 0 ? null : `A${i}: ${c}`))
        .filter(Boolean)
        .join(" · "),
  );
  L.push("");

  // ── Dominant ──
  const eligible = agg.relics.filter((r) => r.owned >= minOwnedForLift);
  const byLift = [...eligible].sort((a, b) => b.lift - a.lift);
  const dominant = byLift.slice(0, 10);
  const dead = [...byLift].reverse().slice(0, 10);

  L.push("## Most DOMINANT relics (highest win-lift)");
  L.push("");
  L.push(`_Win-rate of runs owning the relic minus runs without it. Only relics owned in ≥${minOwnedForLift} runs shown._`);
  L.push("");
  L.push("| Relic | Rarity | Owned | Win% with | Win% without | Lift |");
  L.push("|---|---|--:|--:|--:|--:|");
  for (const r of dominant) {
    L.push(
      `| ${r.name} | ${r.rarity} | ${r.owned} | ${pct(r.winRateWith)} | ${pct(r.winRateWithout)} | **${signPct(r.lift)}** |`,
    );
  }
  L.push("");

  // ── Dead ──
  L.push("## Most DEAD relics (lowest / negative win-lift)");
  L.push("");
  L.push("| Relic | Rarity | Owned | Win% with | Win% without | Lift |");
  L.push("|---|---|--:|--:|--:|--:|");
  for (const r of dead) {
    L.push(
      `| ${r.name} | ${r.rarity} | ${r.owned} | ${pct(r.winRateWith)} | ${pct(r.winRateWithout)} | ${signPct(r.lift)} |`,
    );
  }
  L.push("");

  // ── Never offered / never bought ──
  const neverOffered = agg.relics.filter((r) => r.offered === 0);
  const neverOwned = agg.relics.filter((r) => r.offered > 0 && r.owned === 0);
  const rarelyOwned = agg.relics
    .filter((r) => r.owned > 0 && r.owned < minOwnedForLift)
    .sort((a, b) => a.owned - b.owned);

  L.push("## Coverage gaps");
  L.push("");
  L.push(
    `- **Never offered** (not seen in any draft or shop across ${agg.runs} runs): ` +
      (neverOffered.length ? neverOffered.map((r) => r.name).join(", ") : "_none — every relic appeared_"),
  );
  L.push(
    `- **Offered but never bought** by this policy: ` +
      (neverOwned.length ? neverOwned.map((r) => r.name).join(", ") : "_none_"),
  );
  L.push(
    `- **Rarely owned** (<${minOwnedForLift} runs, too few for a stable lift): ` +
      (rarelyOwned.length ? rarelyOwned.map((r) => `${r.name} (${r.owned})`).join(", ") : "_none_"),
  );
  L.push("");

  // ── Full table ──
  L.push("## Full relic table (by lift)");
  L.push("");
  L.push("| Relic | Rarity | Offered | Owned | OwnedWins | Win% with | Win% without | Lift |");
  L.push("|---|---|--:|--:|--:|--:|--:|--:|");
  const full = [...agg.relics].sort((a, b) => b.lift - a.lift);
  for (const r of full) {
    L.push(
      `| ${r.name} | ${r.rarity} | ${r.offered} | ${r.owned} | ${r.ownedWins} | ${pct(r.winRateWith)} | ${pct(r.winRateWithout)} | ${signPct(r.lift)} |`,
    );
  }
  L.push("");

  // ── Methodology ──
  L.push("## Methodology & caveats");
  L.push("");
  L.push(`- **Word source:** \`an-array-of-english-words\` (${wordCount} words, ≥3 letters) — the game's own dictionary.`);
  L.push("- **Bot word choice:** greedy — the single highest-scoring legal word each play (real engine `scoreWord`, boss `allow` rule, sealed cells, gold tile all honoured). A human deck-builder plays a sequence (Encore/Serpent chains, Alphabet coverage) the greedy bot doesn't optimise for, so combo relics are UNDER-valued here.");
  L.push("- **Shop policy:** " + policy.label + ". Deck edits (add/remove tile) are NOT exercised — the bot keeps its opening deck, so deck-craft's contribution is out of scope.");
  L.push("- **Discards:** the bot re-deals a board when its best word is far below what's needed and a discard remains.");
  L.push("- **Lift is correlational, not causal:** relics co-occur within a run, so a strong engine relic lifts its shelf-mates too. Read lift alongside *owned* count. A hoarding policy owns most of the pool each run, which compresses lift toward zero for everyone — compare policies.");
  L.push(`- **Determinism:** every run is seeded; re-running with the same seed base reproduces these numbers. Runtime: ${(elapsedMs / 1000).toFixed(1)}s for ${agg.runs} runs.`);
  L.push("");

  return L.join("\n");
}
